# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.5.4

    working_directory: ~/spectrum-py

    steps:
      - checkout

      - restore_cache:
          keys:
          - dependencies-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: install depencies
          command: |
            sudo apt-get install virtualenv
            virtualenv -p python3 env
            source env/bin/activate
            pip install pipenv
            pipenv install

      - save_cache:
          paths:
            - ./env
          key: dependencies-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: run test
          command: |
            source env/bin/activate
            export PYTHONPATH=`pwd`
            pytest tests/*

      - store_test_results:
          path: test-reports
          destination: test-reports

workflows:
  version: 2
  run_tests:
    jobs:
      - run_tests
